bom_profissional_content:
    resource: "@BomProfissionalContentBundle/Controller/"
    type:     annotation
    prefix:   /

sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
